const sendOTPEmail = async (email, otp, userName, purpose = 'Email Verification') => {
  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 500px; margin: auto; padding: 20px; border-radius: 8px; background-color: #f9f9f9; border: 1px solid #ddd;">
        
        <!-- Header Section -->
        <div style="text-align: center; background-color: #030711; padding: 15px; border-radius: 8px 8px 0 0;">
          <img src="https://image2url.com/images/1766308878772-0bd91eb0-610c-4afd-b8e6-ef37c05b878d.png" alt="FinSense Logo" style="max-width: 80px;">
          <h2 style="color: #ffffff; margin: 10px 0;">OTP Verification</h2>
        </div>

        <!-- OTP Message -->
        <div style="background-color: #ffffff; padding: 20px; border-radius: 0 0 8px 8px; text-align: center;">
          <p style="font-size: 16px;">Dear <strong>${userName}</strong>,</p>
          <p>Your OTP for <strong>${purpose}</strong> is:</p>
          
          <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin-top: 10px; text-align: center;">
            <h2 style="color: #030711; font-size: 24px; margin: 0;">${otp}</h2>
            <p style="margin-top: 5px; color: red;">This OTP expires in 5 minutes.</p>
          </div>

          <p style="text-align: center; color: gray; font-size: 12px; margin-top: 20px;">
            If you did not request this OTP, please ignore this email.<br>
            Thank you, <br>FinSense Team
          </p>
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">

        <!-- Footer -->
        <p style="color:gray; font-size:12px; text-align: center;">This is an autogenerated message. Please do not reply to this email.</p>
      </div>
    `;

    const response = await fetch(process.env.EMAIL_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.EMAIL_API_KEY}`
      },
      body: JSON.stringify({
        from: process.env.EMAIL,
        to: email,
        subject: '🔐 FinSense OTP Verification',
        html: htmlContent,
        isHtml: true
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("API Error Body:", errorText);
      throw new Error(`Email API failed heavily: ${response.status} ${response.statusText} - ${errorText}`);
    }

  } catch (error) {
    console.error("Failed to send OTP Email:", error);
  }
};

const sendReceiptEmail = async (email, userName, amount, expiryDate) => {
  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 500px; margin: auto; padding: 20px; border-radius: 8px; background-color: #f9f9f9; border: 1px solid #ddd;">
        
        <!-- Header Section -->
        <div style="text-align: center; background-color: #030711; padding: 15px; border-radius: 8px 8px 0 0;">
          <img src="https://image2url.com/images/1766308878772-0bd91eb0-610c-4afd-b8e6-ef37c05b878d.png" alt="FinSense Logo" style="max-width: 80px;">
          <h2 style="color: #ffffff; margin: 10px 0;">Payment Successful!</h2>
        </div>

        <!-- Receipt Message -->
        <div style="background-color: #ffffff; padding: 20px; border-radius: 0 0 8px 8px; text-align: center;">
          <h3 style="color: #16a34a; font-size: 20px; margin: 0 0 15px 0;">₹${amount} paid successfully</h3>
          <p style="font-size: 16px;">Dear <strong>${userName}</strong>,</p>
          <p>Welcome to <strong>FinSense Pro</strong>! Your subscription has been activated.</p>
          
          <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0; text-align: left;">
            <p style="margin: 5px 0;"><strong>Plan:</strong> FinSense Pro (Annual)</p>
            <p style="margin: 5px 0;"><strong>Amount Paid:</strong> ₹${amount}</p>
            <p style="margin: 5px 0;"><strong>Valid Until:</strong> ${new Date(expiryDate).toDateString()}</p>
          </div>

          <p style="font-size: 14px; color: #4b5563;">You now have unlimited access to AI Optimization, Negotiation Assistant, Smart Nudges, and all premium features.</p>

          <p style="text-align: center; color: gray; font-size: 12px; margin-top: 20px;">
            Thank you for upgrading! <br>The FinSense Team
          </p>
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">

        <!-- Footer -->
        <p style="color:gray; font-size:12px; text-align: center;">This is an automated receipt for your recent transaction. Please do not reply to this email.</p>
      </div>
    `;

    const response = await fetch(process.env.EMAIL_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.EMAIL_API_KEY}`
      },
      body: JSON.stringify({
        from: process.env.EMAIL,
        to: email,
        subject: '🎉 FinSense Pro - Payment Receipt',
        html: htmlContent,
        isHtml: true
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("API Error Body:", errorText);
      throw new Error(`Email API failed heavily: ${response.status} ${response.statusText} - ${errorText}`);
    }

  } catch (error) {
    console.error("Failed to send Receipt Email:", error);
  }
};

module.exports = { sendOTPEmail, sendReceiptEmail };