const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL,
    pass: process.env.EMAIL_PASSWORD,
  },
});

const sendOTPEmail = async (email, otp, userName, purpose = 'Email Verification') => {
  const mailOptions = {
    from: process.env.EMAIL,
    to: email,
    subject: '🔐 FinSense OTP Verification',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 500px; margin: auto; padding: 20px; border-radius: 8px; background-color: #f9f9f9; border: 1px solid #ddd;">
        
        <!-- Header Section -->
        <div style="text-align: center; background-color: #030711; padding: 15px; border-radius: 8px 8px 0 0;">
          <img src="https://image2url.com/images/1766308878772-0bd91eb0-610c-4afd-b8e6-ef37c05b878d.png" alt="FinSense Logo" style="max-width: 80px;">
          <h2 style="color: #ffffff; margin: 10px 0;">OTP Verification</h2>
        </div>

        <!-- OTP Message -->
        <div style="background-color: #ffffff; padding: 20px; border-radius: 0 0 8px 8px; text-align: center;">
          <p style="font-size: 16px;">Dear <strong>${userName}</strong>,</p>
          <p>Your OTP for <strong>${purpose}</strong> is:</p>
          
          <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin-top: 10px; text-align: center;">
            <h2 style="color: #030711; font-size: 24px; margin: 0;">${otp}</h2>
            <p style="margin-top: 5px; color: red;">This OTP expires in 5 minutes.</p>
          </div>

          <p style="text-align: center; color: gray; font-size: 12px; margin-top: 20px;">
            If you did not request this OTP, please ignore this email.<br>
            Thank you, <br>FinSense Team
          </p>
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">

        <!-- Footer -->
        <p style="color:gray; font-size:12px; text-align: center;">This is an autogenerated message. Please do not reply to this email.</p>
      </div>
    `,
  };

  await transporter.sendMail(mailOptions);
};

module.exports = { sendOTPEmail };